Fix for https://github.com/diggerhq/digger/issues/768
diggerhq/digger pull request #769
Opened 2023-11-12 19:06 UTC by ajaxian79

Moved and refactored panic recovery into the main func and removed from individual ci handlers for a consolidated flow.

2023-11-14 07:25 UTC, motatoes commented
tests were not triggered for some reason so I will be closing and re-opening to try and trigger them

2023-11-14 10:03 UTC, motatoes commented on cmd/digger/main.go
> +		parsedAzureContext, _ := azure.GetAzureReposContext(azureContext)
My only concern is that in this case the work for parsing payload will be done twice

It is a minor task but we should probably convert those parsers into singletons in the future

Should be OK to merge for now but can we make a note on top of this line with a comment which says something like "TODO: refactor this function to make it not perform double work after calling the `acureCI` function"

2023-11-14 10:13 UTC, motatoes requested changes
Could we just add a comment on the azure section for refactoring in the future? And then its good to go 👍

2023-11-15 04:43 UTC, ajaxian79 commented
@motatoes I will definitely add a comment when I shoot a follow up video this weekend, thanks!  I may even take a stab at refactoring

2023-11-19 06:35 UTC, motatoes approved these changes

2023-11-19 06:35 UTC, motatoes commented
❤️  thanks for your contribution @ajaxian79

2023-11-19 06:35 UTC, merged

2023-11-19 06:38 UTC, ajaxian79 commented
> ❤️  thanks for your contribution @ajaxian79 

It was my genuine pleasure and I look forward to contributing more in the future!