Implement Help and Version Commands
diggerhq/digger pull request #96
Opened 2023-04-01 13:45 UTC by s1ntaxe770r

This PR adds version and help commands to the digger CLI
As requested in  #18

2023-04-03 10:46 UTC, Spartakovic commented on pkg/utils/commands.go
> +	{"digger lock", "Lock Terraform state"},
there is digger unlock too. Also it doesn't lock terraform state, it rather locks terraform projects on pull request level

2023-04-03 10:46 UTC, Spartakovic commented on pkg/utils/commands.go
> +	{"digger plan", "Plan digger configuration"},
it doesn't apply digger configuration, but terraform configuration. It just adds few more things on top, like locking

2023-04-03 13:31 UTC, motatoes commented
In addition to being invoked as a cli command, digger is also invoked as part of github action in which case the arguments are github context. We also want to react to a comment in the pull request and publish a comment in result. We can do this [here](https://github.com/diggerhq/digger/blob/3fffbdcc2073de471f92e2f3a634b251008cbdd0/cmd/digger/main.go#L59-L58) after detecting that the event is a comment and the comment is "digger help" then publish a comment as a result to it and exit(0)

2023-04-04 10:16 UTC, motatoes requested changes
few last changes, but looking good so far

2023-04-04 10:16 UTC, motatoes commented on cmd/digger/main.go
> +	}
I suggest to do it like this

```suggestion
	if digger.CheckIfHelpComment(ghEvent) {
		reply := utils.GetCommands()
		githubPrService.PublishComment(prNumber, reply)
	}
```

Where you can define the function of `CheckIfHelpComment` as follows in digger.go

```
func CheckIfHelpComment(event models.Event) bool {
	switch event.(type) {
	case models.IssueCommentEvent:
		event := event.(models.IssueCommentEvent)
		if strings.Contains(event.Comment.Body, "digger help") {
			return true
		}
	}
	return false
}
```

2023-04-04 10:16 UTC, motatoes commented on pkg/github/github.go
> +	ReplyComment(prNumber int, reply string)
This function is not needed at all

2023-04-04 15:22 UTC, motatoes approved these changes

2023-04-04 15:24 UTC, merged